# Generated by Django 3.1.3 on 2021-01-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_status', models.PositiveSmallIntegerField()),
                ('response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ip_address', models.CharField(max_length=127)),
                ('is_timeout', models.BooleanField(default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
    ]
