# Generated by Django 3.1.3 on 2021-01-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('live_probes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveprobe',
            name='http_status',
        ),
        migrations.AddField(
            model_name='liveprobe',
            name='error_type',
            field=models.CharField(max_length=127, null=True, verbose_name='Error type'),
        ),
        migrations.AddField(
            model_name='liveprobe',
            name='http_status_code',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='HTTP code'),
        ),
        migrations.AddField(
            model_name='liveprobe',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='liveprobe',
            name='ip_address',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='liveprobe',
            name='is_timeout',
            field=models.BooleanField(default=False, verbose_name='Timedout accured'),
        ),
        migrations.AlterField(
            model_name='liveprobe',
            name='response_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Response time'),
        ),
        migrations.AlterField(
            model_name='liveprobe',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_probes', to='websites.website'),
        ),
    ]
